baseURL = "https://alanpruitt.com/"
enableMissingTranslationPlaceholders = false

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

[languages]
  [languages.en]
    languageName = "EN"
    languageCode = "en-US"
    contentDir = "content/en"
    weight = 1
    title = "Coach Alan"

  [languages.es]
    languageName = "ES"
    languageCode = "es-MX"
    contentDir = "content/es"
    weight = 2
    title = "Coach Alan"
