baseURL = "https://alanpruitt.github.io/alanpruitt/"
languageCode = "en-us"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true
enableMissingTranslationPlaceholders = false

[languages.en]
languageName = "English"
weight = 1
title = "Coach Alan"
languageCode = "en-US"

[languages.es]
languageName = "Español (Norteño)"
weight = 2
title = "Coach Alan"
languageCode = "es-MX"
