[build]
  command = "hugo --minify"
  publish = "public"

[context.production.environment]
  HUGO_VERSION = "0.125.0" # Or your current Hugo version
  HUGO_ENV = "production"
  HUGO_ENABLELARGESTINGS = "true"
